2025-03-25 13:54:36,028 - ERROR - cannot access local variable 'permisos' where it is not associated with a value - permisosPerfilData.py:322
